{{- $def := index .Values "default" -}}
# Source: prometheus-operator/charts/grafana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: release-grafana
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-4.3.2
    release: release
    heritage: Tiller
type: Opaque
data:
  admin-user: "YWRtaW4="
  admin-password: "cHJvbS1vcGVyYXRvcg=="
  ldap-toml: ""
