{{- $def := index .Values "default" -}}
# Source: prometheus-operator/charts/grafana/templates/tests/test-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-grafana-test
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-4.3.2
    heritage: Tiller
    release: release
rules:
- apiGroups:      ['policy']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [release-grafana-test]
