{{- $def := index .Values "default" -}}
# Source: prometheus-operator/charts/grafana/templates/tests/test-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: grafana
    chart: grafana-4.3.2
    heritage: Tiller
    release: release
  name: release-grafana-test
  namespace: monitoring
