{{- $def := index .Values "default" -}}
# Source: prometheus-operator/charts/grafana/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-grafana
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-4.3.2
    release: release
    heritage: Tiller
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 80
      protocol: TCP
      targetPort: 3000

  selector:
    app: grafana
    release: release
