{{- $def := index .Values "default" -}}
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-release-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Tiller
    release: release
    chart: prometheus-node-exporter-1.8.1
    jobLabel: node-exporter
    
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - release-prometheus-node-exporter
