{{- $def := index .Values "default" -}}
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/psp-clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp-release-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Tiller
    release: release
    chart: prometheus-node-exporter-1.8.1
    jobLabel: node-exporter
    
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp-release-prometheus-node-exporter
subjects:
  - kind: ServiceAccount
    name: release-prometheus-node-exporter
    namespace: monitoring
