{{- $def := index .Values "default" -}}
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: release-prometheus-node-exporter
  namespace: monitoring
  labels:     
    app: prometheus-node-exporter
    heritage: Tiller
    release: release
    chart: prometheus-node-exporter-1.8.1
    jobLabel: node-exporter
    
spec:
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: release
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:         
        app: prometheus-node-exporter
        heritage: Tiller
        release: release
        chart: prometheus-node-exporter-1.8.1
        jobLabel: node-exporter
        
    spec:
      serviceAccountName: release-prometheus-node-exporter
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        
      containers:
        - name: node-exporter
          image: "{{ .Values.nodeexporterimage.repository }}:{{ .Values.nodeexporterimage.tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
            - --web.listen-address=0.0.0.0:9100
            - --collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)
            - --collector.filesystem.ignored-fs-types=^(autofs|binfmt_misc|cgroup|configfs|debugfs|devpts|devtmpfs|fusectl|hugetlbfs|mqueue|overlay|proc|procfs|pstore|rpc_pipefs|securityfs|sysfs|tracefs)$
            
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9100
          readinessProbe:
            httpGet:
              path: /
              port: 9100
          resources:
            {}
            
          volumeMounts:
            - name: proc
              mountPath: /host/proc
              readOnly:  true
            - name: sys
              mountPath: /host/sys
              readOnly: true
      hostNetwork: true
      hostPID: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
        
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: sys
          hostPath:
            path: /sys
