{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/exporters/kube-scheduler/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-prometheus-operato-kube-scheduler
  namespace: monitoring
  labels:
    app: prometheus-operator-kube-scheduler
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-operator-kube-scheduler
      release: "release"
  namespaceSelector:
    matchNames:
      - "kube-system"
  endpoints:
  - port: http-metrics
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
