{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/grafana/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: release-prometheus-operato-grafana
  namespace: monitoring
  labels:
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: grafana
      release: "release"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: service
    path: "/metrics"
