apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: new-snapshot-test
spec:
  source:
    persistentVolumeClaimName: prometheus-release-prometheus-operato-prometheus-db-prometheus-release-prometheus-operato-prometheus-0
