# Source: prometheus-operator/templates/grafana/configmaps-datasources.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: release-prometheus-operato-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://release-prometheus-operato-prometheus:9090/
      access: proxy
      isDefault: true
