{{- $def := index .Values "default" -}}
# release-prometheus-operato-admission-create
apiVersion: batch/v1
kind: Job
metadata:
  name:  release-prometheus-operato-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission-create    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
spec:
  template:
    metadata:
      name:  release-prometheus-operato-admission-create
      labels:
        app: prometheus-operator-admission-create        
        chart: prometheus-operator-8.7.0
        release: "release"
        heritage: "Tiller"
    spec:
      containers:
        - name: create
          image: "{{ .Values.admission.repository }}:{{ .Values.admission.tag }}"
          imagePullPolicy: 
          args:
            - create
            - --host=release-prometheus-operato-operator,release-prometheus-operato-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=release-prometheus-operato-admission
          resources:
            {}
            
      restartPolicy: OnFailure
      serviceAccountName: release-prometheus-operato-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
