{{- $def := index .Values "default" -}}
# release-prometheus-operato-admission
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name:  release-prometheus-operato-admission
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - update
  - apiGroups: ['extensions']
    resources: ['podsecuritypolicies']
    verbs:     ['use']
    resourceNames:
    - release-prometheus-operato-admission
