{{- $def := index .Values "default" -}}
# release-prometheus-operato-admission
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name:  release-prometheus-operato-admission
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-prometheus-operato-admission
subjects:
  - kind: ServiceAccount
    name: release-prometheus-operato-admission
    namespace: monitoring
