{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/alertmanager/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-prometheus-operato-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
imagePullSecrets:
  []
