{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/alertmanager/psp-rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-prometheus-operato-alertmanager
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-prometheus-operato-alertmanager
subjects:
  - kind: ServiceAccount
    name: release-prometheus-operato-alertmanager
    namespace: monitoring
