{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/exporters/kube-etcd/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-prometheus-operato-kube-etcd
  labels:
    app: prometheus-operator-kube-etcd
    jobLabel: kube-etcd
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 2379
      protocol: TCP
      targetPort: 2379
  selector:
    component: etcd
  type: ClusterIP
