{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/exporters/kube-scheduler/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-prometheus-operato-kube-scheduler
  labels:
    app: prometheus-operator-kube-scheduler
    jobLabel: kube-scheduler
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10251
      protocol: TCP
      targetPort: 10251
  selector:
    component: kube-scheduler
  type: ClusterIP
