{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/prometheus/psp-clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-prometheus-operato-prometheus-psp
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - release-prometheus-operato-prometheus
