{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/prometheus/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-prometheus-operato-prometheus
  namespace: monitoring
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
imagePullSecrets:
  []
