{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/prometheus-operator/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-prometheus-operato-operator
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: release-prometheus-operato-operator
subjects:
- kind: ServiceAccount
  name: release-prometheus-operato-operator
  namespace: monitoring
