{{- $def := index .Values "default" -}}
# Source: prometheus-operator/templates/exporters/kube-proxy/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: release-prometheus-operato-kube-proxy
  labels:
    app: prometheus-operator-kube-proxy
    jobLabel: kube-proxy
    
    chart: prometheus-operator-8.7.0
    release: "release"
    heritage: "Tiller"
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 10249
      protocol: TCP
      targetPort: 10249
  selector:
    k8s-app: kube-proxy
  type: ClusterIP
